# See https://docs.codecov.io/docs/codecovyml-reference
codecov:
  token: b5e588e8-7b85-46f1-bad6-e0a5c19d7d67
  require_ci_to_pass: no  # codecov reports its results independent of whether CI passed
  notify:
    wait_for_ci: no       # codecov has not to wait until the CI is finished to post its results

coverage:
  status:
    project:  # project is the overall code coverage of the whole codebase
      default:
        if_ci_failed: success # per default, codecov would fail if any CI fails
        informational: true   # the codecov/patch status is never "fail"
    patch:  # patch is the code-coverage of the changed lines in the PR and often reports false positives
      default:
        if_ci_failed: success # per default, codecov would fail if any CI fails
        informational: true   # the codecov/patch status is never "fail"
        only_pulls: true      # only post codecov/patch status on PRs
