# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

blank_issues_enabled: true
contact_links:
  - name: Questions and Answers
    url: https://github.com/seqan/sharg-parser/discussions
    about: Ask us about installing and using Sharg in our discussions forum!
