# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Coverage

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.compiler }}
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        compiler: ["gcc-14"]
    container:
      image: ghcr.io/seqan/${{ matrix.compiler }}
      volumes:
        - /home/runner:/home/runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Load ccache
        uses: actions/cache@v4
        with:
          path: /home/runner/.ccache
          key: ccache-${{ runner.os }}-${{ github.workflow }}-${{ matrix.compiler }}-${{ github.ref }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ github.workflow }}-${{ matrix.compiler }}-${{ github.ref }}
            ccache-${{ runner.os }}-${{ github.workflow }}-${{ matrix.compiler }}

      - name: Increase ccache size
        run: echo "CCACHE_MAXSIZE=300M" >> "${GITHUB_ENV}"

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake ../test/coverage -DCMAKE_BUILD_TYPE=Coverage
          make gtest_build yaml-cpp

      - name: Build tests
        working-directory: build
        run: |
          ccache -z
          make -k
          ccache -svvx

      - name: Run tests
        working-directory: build
        run: ctest . -j --output-on-failure --no-tests=error

      - name: Generate coverage report
        run: |
          gcovr --root ${GITHUB_WORKSPACE}/test/coverage \
                ${GITHUB_WORKSPACE}/build \
                --filter ${GITHUB_WORKSPACE}/include/sharg \
                --filter ${GITHUB_WORKSPACE}/test/include/sharg/test \
                --exclude ${GITHUB_WORKSPACE}/include/sharg/contrib \
                --exclude ${GITHUB_WORKSPACE}/include/sharg/std \
                --exclude-lines-by-pattern '^\s*$' \
                --exclude-lines-by-pattern '^\s*};$' \
                --exclude-unreachable-branches \
                --exclude-throw-branches \
                --exclude-noncode-lines \
                -j \
                --cobertura \
                --output ${GITHUB_WORKSPACE}/build/coverage_report.xml

      - name: Submit coverage build
        uses: codecov/codecov-action@v3.1.5
        with:
          files: build/coverage_report.xml
          fail_ci_if_error: false
